/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelRouteImport } from './routes/cel'
import { Route as DrRouteImport } from './routes/dr'
import { Route as PengaturanRouteImport } from './routes/pengaturan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelRoute = CelRouteImport.update({
  id: '/cel',
  path: '/cel',
  getParentRoute: () => rootRouteImport,
} as any)
const DrRoute = DrRouteImport.update({
  id: '/dr',
  path: '/dr',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cel': typeof CelRoute
  '/dr': typeof DrRoute
  '/pengaturan': typeof PengaturanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cel': typeof CelRoute
  '/dr': typeof DrRoute
  '/pengaturan': typeof PengaturanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cel': typeof CelRoute
  '/dr': typeof DrRoute
  '/pengaturan': typeof PengaturanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cel' | '/dr' | '/pengaturan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cel' | '/dr' | '/pengaturan'
  id: '__root__' | '/' | '/cel' | '/dr' | '/pengaturan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelRoute: typeof CelRoute
  DrRoute: typeof DrRoute
  PengaturanRoute: typeof PengaturanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cel': {
      id: '/cel'
      path: '/cel'
      fullPath: '/cel'
      preLoaderRoute: typeof CelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr': {
      id: '/dr'
      path: '/dr'
      fullPath: '/dr'
      preLoaderRoute: typeof DrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelRoute: CelRoute,
  DrRoute: DrRoute,
  PengaturanRoute: PengaturanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
